# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  夜狼之神
subtitle: 菜鸟之路
name: 夜狼之神 
email: illy623@163.com
description: 本站是夜狼之神的技术分享博客。内容涵盖生活故事、Java后端技术、Java前端技术、Spring Boot、知识分享。
keywords: 夜狼之神,Spring Boot,VUE
encoding: "utf-8"
favicon: favicon.ico 

repository: shanuotian/shanuotian.github.io
github_url: https://github.com/shanuotian
url: https://shanuotian.github.io

#enforce_ssl: ityouknow.com


## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
#
#  -
#    href: /python.html
#    label: Python  
#    target: _blank
#
  -
    href: /it.html
    label: IT
    target: _blank
#
#  -
#    href: /zsxq.html
#    label: 星球
#    target: _blank   
#
#  -
#    href: /life.html
#    label: 故事
#    target: _blank
#
#  -
#    href: /arch.html
#    label: 架构
#    target: _blank
#
  -
    href: /link.html
    label: 友链
    target: _blank



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot.html
    label: Spring Boot
    target: _blank
#    subnav:

#      -
#        subHref: /spring-boot.html
#        subLabel: Spring Boot
#
#      -
#        subHref: /spring-cloud.html
#        subLabel: Spring Cloud

  -
    href: /vue.html
    label: vue
    target: _blank

#  -
#    href: /spring-cloud.html
#    label: Spring Cloud
#    target: _blank

#  -
#    
#    href: http://www.justdojava.com
#    label: Java
#    target: _blank
#    subnav:
#
#      -
#        subHref: /java.html
#        subLabel: Jvm 系列文章
#        
#     -
#        subHref: http://www.justdojava.com
#        subLabel: Java 极客技术
#        target: _blank

#  -
#    href: /archives.html
#    label: Archives
#    target: _blank

#  -
#    href: /about.html
#    label: About
#    target: _blank


# labels. my blog key words
#labels:

#  -
#    href: /payment.html
#    label: 支付     
#    target: _blank

#  -
#    href: /fastdfs.html
#    label: FastDFS
#    target: _blank

#  -
#    href: /mongodb.html
#    label: MongoDB
#    target: _blank

#  -
#    href: /docker.html
#    label: Docker
#    target: _blank

#  -
#    href: /open-source.html
#    label: Code  
#    target: _blank

#  -
#    href: /gitchat.html
#    label: Chat
#    target: _blank

#  -
#    href: /geektime.html
#    label: 极客
#    target: _blank


# selected articles
#classes:
#
#  -
#    href: /life.html
#    name: 我的故事
#    describe: 生活就是故事，故事就是生活

#  -
#    href: /arch.html
#    name: 架构师之路
#    describe: 一个架构师的自我修养

#  -
#    href: /java.html
#    name: Java 系列文章
#    describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
#skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
#skill_j2ee_keywords: [Spring, MyBatis, JPA]
#skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis,  Boostrap]
#skill_mobile_app_keywords: [vuejs]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: shanuotian
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: shanuotian
    repo: shanuotian.github.io
    oauth:
        client_id: 8cb872ed9b94621da678
        client_secret: 4a8f72be677265baa0abfaa539b6e8b7c4799ced
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: shanuotian
    repo: shanuotian.github.io
    clientID: 8cb872ed9b94621da678
    clientSecret: 4a8f72be677265baa0abfaa539b6e8b7c4799ced
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : true
theme: jekyll-theme-architect